### PR TITLE
Fix Actor.Orientation field size: correct size is 4 bytes, not 2

### PR DESCRIPTION
**Pull request by Mingun**
See https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Entrance,
    https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v9.1.htm#formAREAV9_1_Entrance
and https://github.com/gemrb/gemrb/blob/edb1603d9432d1bd5a7b4a73788a9f1242772df4/gemrb/plugins/AREImporter/AREImporter.cpp#L1246-L1258

Also, Actor.Orientation field is also 2 bytes (Entrance.Orientation uses the same bitmap for decode values, so these fields are connected in some way).

@lynxlynxlynx, @Argent77 your opinion will be welcome!

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
LGTM. It doesn't matter that much, since the rest of the fields are unused, but I didn't run an exhaustive check to see if any garbage is there that could pollute the current dword. Orientation is mostly a dword elsewhere, but since it can be max 15, nobody cares.

**Comment by Mingun** [comment]
> Orientation is mostly a dword elsewhere, but since it can be max 15, nobody cares.

If so, it is better to correct incorrect types elsewhere. I did an additional invertigation.

`Actor.s_orientation` (description of orientation flags in NI) is used in 4 places:
1. When creating effect [Move creature (186)](https://gibberlings3.github.io/iesdp/opcodes/bg2tob.htm#op186) effect in BG2:
    https://github.com/NearInfinityBrowser/NearInfinity/blob/e4e5cb0ed3c2afcb2ee5f15737de665a2829687c/src/org/infinity/resource/EffectFactory.java#L3106-L3114
    this code is called from several places, one of it is reading EFF resource. G3 describes it as:
    - [EFF v1](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v1.htm)
    - [EFF v2](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm)
    Only EFF v2 has separate file, and according to the NI code, orientation stored in field `Parameter 2`. As I see, this is some generic parameter, so it size do not prove anything.
2. Reading `Actor`. In this place 2 bytes is used, but then immediately goes 2 unknown bytes.
    https://github.com/NearInfinityBrowser/NearInfinity/blob/e4e5cb0ed3c2afcb2ee5f15737de665a2829687c/src/org/infinity/resource/are/Actor.java#L209-L212
    G3 says 2 bytes here:
    - [ARE v1](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Actor)
    - [ARE v9.1](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v9.1.htm#formAREAV9_1_Actor)
    gemrb reads 4 bytes:
    https://github.com/gemrb/gemrb/blob/c6084d1a6220bf9aef54de389252d95101d1a4aa/gemrb/plugins/AREImporter/AREImporter.cpp#L1094-L1096
3. Reading `Entrance`, where it is 4 bytes:
    https://github.com/NearInfinityBrowser/NearInfinity/blob/e4e5cb0ed3c2afcb2ee5f15737de665a2829687c/src/org/infinity/resource/are/Entrance.java#L47-L55
    G3 uses 2 bytes:
    - [ARE v1](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Entrance),
    - [ARE v9.1](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v9.1.htm#formAREAV9_1_Entrance)
    gemrb reads 2 bytes
    https://github.com/gemrb/gemrb/blob/edb1603d9432d1bd5a7b4a73788a9f1242772df4/gemrb/plugins/AREImporter/AREImporter.cpp#L1246-L1258
4. Reading `PartyNPC`, where it is 4 bytes:
    https://github.com/NearInfinityBrowser/NearInfinity/blob/e4e5cb0ed3c2afcb2ee5f15737de665a2829687c/src/org/infinity/resource/gam/PartyNPC.java#L223-L231
    G3 uses 4 bytes:
    - [GAM v1.1](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v1.1.htm#GAMEV1_1_NPC)
    - [GAM v2.0](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v2.0.htm#GAMEV2_0_NPC)
    - [GAM v2.2](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v2.2.htm#GAMEV2_2_NPC)
    gemrb uses 4 bytes:
    https://github.com/gemrb/gemrb/blob/c6084d1a6220bf9aef54de389252d95101d1a4aa/gemrb/plugins/GAMImporter/GAMImporter.cpp#L340-L354

----
So, I think, that we must fix:
- Description on G3:
    - [ARE v1 Actor](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Actor)
    - [ARE v9.1 Actor](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v9.1.htm#formAREAV9_1_Actor)
    - [ARE v1 Entrance](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Entrance),
    - [ARE v9.1 Entrance](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v9.1.htm#formAREAV9_1_Entrance)
- NearInfinity:
    https://github.com/NearInfinityBrowser/NearInfinity/blob/e4e5cb0ed3c2afcb2ee5f15737de665a2829687c/src/org/infinity/resource/are/Actor.java#L209-L212
- gemrb:
    https://github.com/gemrb/gemrb/blob/edb1603d9432d1bd5a7b4a73788a9f1242772df4/gemrb/plugins/AREImporter/AREImporter.cpp#L1246-L1258

**Comment by lynxlynxlynx** [comment]
I don't know, there's no reason why they should all be the same internally or even just stored. Plenty of assumptions there and IEs are known to be full of depravity. Especially there's no guarantee that the orientation field for Entrance and the one for Actor are the same, since these are unrelated structures.

**Comment by Argent77** [comment]
According to the [structure definitions](https://forums.beamdog.com/discussion/comment/10544/#Comment_10544) provided by devs who had access to the game sources, it looks like ARE V1 Actor orientation is indeed just a WORD field, followed by 2 bytes of padding. It's fairly safe to assume that Actor orientation in ARE V9.1 uses the same size.

I'm closing this issue.

**Pull request closed without merging**
